#!/usr/bin/env bash
#
# dev.sh — single entrypoint for local development and demo of Transact.
#
# Wraps docker compose, Maven, Node/Playwright, and (optionally) k6 so a
# fresh clone can go from zero to a running, demonstrable stack with one
# command, without memorizing the individual tool invocations documented in
# README.md.
#
# Usage: ./dev.sh <command> [options]
#
# Run './dev.sh help' for the full command list.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

ENV_FILE="$ROOT/.env"
CERT_DIR="$ROOT/certs"
COMPOSE_BASE=(-f docker-compose.yml)
COMPOSE_TLS=(-f docker-compose.yml -f docker-compose.tls.yml)
DEFAULT_CUSTOMER_ID="00000000-0000-0000-0000-000000000001"

# ---------------------------------------------------------------------------
# Output helpers
# ---------------------------------------------------------------------------

if [[ -t 1 ]] && [[ -z "${NO_COLOR:-}" ]]; then
  C_INFO=$'\033[36m'; C_OK=$'\033[32m'; C_WARN=$'\033[33m'; C_ERR=$'\033[31m'; C_RESET=$'\033[0m'
else
  C_INFO=""; C_OK=""; C_WARN=""; C_ERR=""; C_RESET=""
fi

log_info() { printf '%s[dev.sh]%s %s\n' "$C_INFO" "$C_RESET" "$*"; }
log_ok()   { printf '%s[dev.sh]%s %s\n' "$C_OK" "$C_RESET" "$*"; }
log_warn() { printf '%s[dev.sh]%s %s\n' "$C_WARN" "$C_RESET" "$*" >&2; }
log_err()  { printf '%s[dev.sh]%s %s\n' "$C_ERR" "$C_RESET" "$*" >&2; }

require_cmd() {
  local cmd="$1" hint="${2:-}"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    log_err "Required tool '$cmd' not found on PATH.${hint:+ $hint}"
    exit 1
  fi
}

# ---------------------------------------------------------------------------
# Environment / compose plumbing
# ---------------------------------------------------------------------------

# Idempotent: writes .env with fresh dev-only secrets only if it doesn't
# already exist. Never overwrites — a hand-edited .env is left alone.
ensure_env_file() {
  if [[ -f "$ENV_FILE" ]]; then
    return 0
  fi
  require_cmd openssl "Install openssl to auto-generate dev secrets, or copy .env.example to .env by hand."
  log_info "No .env found — generating one with fresh dev-only secrets (never committed; see .gitignore)."
  local pg_password jwt_secret
  pg_password="$(openssl rand -hex 24)"
  jwt_secret="$(openssl rand -base64 48 | tr -d '\n')"
  cat > "$ENV_FILE" <<EOF
# Generated by ./dev.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) — dev-only secrets. Never commit this file.
# Regenerate at any time by deleting .env and re-running ./dev.sh setup (or start).
POSTGRES_PASSWORD=$pg_password
SPRING_DATASOURCE_PASSWORD=$pg_password
APP_SECURITY_JWT_SECRET=$jwt_secret
APP_INGESTION_INTERVAL_MS=60000
EOF
  log_ok "Wrote $ENV_FILE"
}

# Sources .env into the current shell so this script can mint JWTs with the
# same secret the running server uses (scripts/mint-jwt.mjs otherwise falls
# back to a hard-coded test secret — see docs/principal_engineer_review_report.md L-03).
load_env() {
  if [[ ! -f "$ENV_FILE" ]]; then
    log_err "No .env found. Run './dev.sh setup' first."
    exit 1
  fi
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
}

# Populates the global COMPOSE_FILES array and BASE_URL for the given TLS flag.
compose_context() {
  local tls="$1"
  if [[ "$tls" == "1" ]]; then
    COMPOSE_FILES=("${COMPOSE_TLS[@]}")
    BASE_URL="https://localhost:8443"
    CURL_TLS_FLAG="-k"
  else
    COMPOSE_FILES=("${COMPOSE_BASE[@]}")
    BASE_URL="http://localhost:8080"
    CURL_TLS_FLAG=""
  fi
}

compose() {
  docker compose "${COMPOSE_FILES[@]}" "$@"
}

require_certs() {
  if [[ ! -f "$CERT_DIR/localhost.p12" ]]; then
    log_err "No local TLS certs found at $CERT_DIR. Run './dev.sh certs' first."
    exit 1
  fi
}

mint_token() {
  # $1=roles (CUSTOMER|ADMIN), $2=customerId
  E2E_ROLES="$1" E2E_CUSTOMER_ID="$2" node "$ROOT/scripts/mint-jwt.mjs"
}

curl_json() {
  curl -fsS $CURL_TLS_FLAG "$@"
}

# ---------------------------------------------------------------------------
# help
# ---------------------------------------------------------------------------

cmd_help() {
  cat <<'EOF'
dev.sh — run and demo Transact locally with one script.

USAGE
  ./dev.sh <command> [options]

LIFECYCLE
  setup                 One-time bootstrap: checks prerequisites, generates
                         .env (dev-only secrets) if missing, and builds the
                         app image. Safe to re-run.
  certs [--force]       Generate a local self-signed dev CA + TLS keystore
                         under certs/ for the API's optional local HTTPS
                         listener (./dev.sh start --tls). --force regenerates
                         even if certs already exist.
                         NOTE: this covers the API's own listener only.
                         Postgres/Kafka traffic stays plaintext locally —
                         that is Phase 9 ("Bank Production Readiness") scope
                         in IMPLEMENTATION_PLAN.md, not delivered here.
  start [--build] [--tls] [--wait-timeout N]
                         Start postgres, zookeeper, kafka, the API,
                         prometheus, and grafana, and wait for health.
                         --build forces an image rebuild. --tls serves the
                         API over HTTPS on :8443 using certs/ (run
                         './dev.sh certs' first).
  stop [--volumes] [--tls]
                         Stop the stack. --volumes also deletes the Postgres
                         data volume (destructive — asks to confirm).
  restart [--build] [--tls]
                         stop then start with the same flags.
  status [--tls]         Container states + a live health/readiness summary.
  logs [service...] [-f|--follow] [--tail N] [--tls]
                         Tail compose logs, optionally for specific services
                         (postgres, kafka, transaction-api, prometheus,
                         grafana, zookeeper).

DEMO DATA
  seed [--timeout SECONDS] [--tls]
                         Waits for the stack to be healthy, then polls
                         /v1/admin/sources until every source has completed
                         at least one ingestion cycle, then runs one example
                         authenticated query against the seeded demo
                         customer and prints it. (The demo customer/accounts
                         themselves are seeded automatically by the Flyway
                         V2 migration — this command proves the ingestion ->
                         categorization -> API path actually works end to
                         end, and hands you a ready-to-use JWT.)

TESTING
  test [--unit | --e2e] Runs the Maven test suite (unit + Testcontainers
                         integration) by default. --unit runs only the
                         subset that does not need Testcontainers (fast,
                         no Docker required). --e2e runs the Playwright
                         suite against an already-running stack (start it
                         first) with the same zero-skipped assertion CI uses.
  perf [--scenario smoke|load|soak|all] [--vus N] [--hold Ns] [--customer-id ID] [--tls]
                         Runs the k6 load test (scripts/load-test.js)
                         against a running stack. Default scenario is
                         'smoke' (fast sanity check, ~10s); pass 'load' or
                         'soak' for a real capacity run (verified numbers:
                         IMPLEMENTATION_PLAN.md Phase 7). Uses a local k6
                         binary if present, otherwise falls back to the
                         official grafana/k6 Docker image — no local
                         install required either way.

OTHER
  clean                  Alias for 'stop --volumes'.
  help                    This message.

EXAMPLES
  ./dev.sh setup && ./dev.sh start && ./dev.sh seed
  ./dev.sh logs transaction-api -f
  ./dev.sh test --unit
  ./dev.sh perf --scenario load --vus 20 --hold 2m
  ./dev.sh start --tls   # local HTTPS demo
EOF
}

# ---------------------------------------------------------------------------
# setup
# ---------------------------------------------------------------------------

cmd_setup() {
  log_info "Checking prerequisites..."
  require_cmd docker "Install Docker Desktop / Docker Engine."
  if ! docker compose version >/dev/null 2>&1; then
    log_err "'docker compose' (v2 plugin) is required. Update Docker Desktop/Engine."
    exit 1
  fi
  require_cmd java "Install JDK 21+."
  require_cmd mvn "Install Maven 3.9+ (or use ./scripts/test.sh which wraps mvn)."
  require_cmd node "Install Node.js (used for JWT minting and Playwright/k6 helpers)."
  require_cmd openssl "Install openssl (used for .env secrets and ./dev.sh certs)."
  if ! command -v jq >/dev/null 2>&1; then
    log_warn "jq not found — 'status' and 'seed' output will be less readable, but will still work."
  fi
  log_ok "Prerequisites OK."

  ensure_env_file

  log_info "Building the application image (docker compose build transaction-api)..."
  compose_context 0
  compose build transaction-api

  log_ok "Setup complete. Next: ./dev.sh start"
}

# ---------------------------------------------------------------------------
# certs
# ---------------------------------------------------------------------------

cmd_certs() {
  local force=0
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --force) force=1; shift ;;
      *) log_err "Unknown option for certs: $1"; exit 1 ;;
    esac
  done

  require_cmd openssl "Install openssl."

  if [[ -f "$CERT_DIR/localhost.p12" && "$force" -eq 0 ]]; then
    log_info "Certs already exist at $CERT_DIR (use --force to regenerate)."
    return 0
  fi

  mkdir -p "$CERT_DIR"
  chmod 700 "$CERT_DIR"

  log_info "Generating local dev CA + server certificate for localhost (self-signed, dev-only)..."

  openssl req -x509 -new -nodes -newkey rsa:4096 -sha256 -days 825 \
    -keyout "$CERT_DIR/dev-ca.key" -out "$CERT_DIR/dev-ca.crt" \
    -subj "/CN=Transact Local Dev CA" >/dev/null 2>&1

  openssl req -new -nodes -newkey rsa:2048 \
    -keyout "$CERT_DIR/localhost.key" -out "$CERT_DIR/localhost.csr" \
    -subj "/CN=localhost" >/dev/null 2>&1

  openssl x509 -req -in "$CERT_DIR/localhost.csr" \
    -CA "$CERT_DIR/dev-ca.crt" -CAkey "$CERT_DIR/dev-ca.key" -CAcreateserial \
    -out "$CERT_DIR/localhost.crt" -days 825 -sha256 \
    -extfile <(printf "subjectAltName=DNS:localhost,DNS:transaction-api,IP:127.0.0.1") \
    >/dev/null 2>&1

  local keystore_password
  keystore_password="$(openssl rand -hex 16)"

  openssl pkcs12 -export \
    -in "$CERT_DIR/localhost.crt" -inkey "$CERT_DIR/localhost.key" \
    -certfile "$CERT_DIR/dev-ca.crt" -name transact \
    -out "$CERT_DIR/localhost.p12" -password "pass:$keystore_password" \
    >/dev/null 2>&1

  rm -f "$CERT_DIR/localhost.csr" "$CERT_DIR/dev-ca.srl"
  chmod 600 "$CERT_DIR"/*.key "$CERT_DIR/localhost.p12" 2>/dev/null || true

  ensure_env_file
  if grep -q '^SERVER_SSL_KEY_STORE_PASSWORD=' "$ENV_FILE" 2>/dev/null; then
    # Replace any previous value (e.g. after --force regeneration).
    local tmp
    tmp="$(mktemp)"
    grep -v '^SERVER_SSL_KEY_STORE_PASSWORD=' "$ENV_FILE" > "$tmp"
    mv "$tmp" "$ENV_FILE"
  fi
  echo "SERVER_SSL_KEY_STORE_PASSWORD=$keystore_password" >> "$ENV_FILE"

  log_ok "Certs written to $CERT_DIR (gitignored). Keystore password stored in .env."
  log_warn "Local dev only: self-signed, API listener only. Postgres/Kafka stay plaintext" \
           "(IMPLEMENTATION_PLAN.md Phase 9, not delivered). Use './dev.sh start --tls' to try it."
}

# ---------------------------------------------------------------------------
# start / stop / restart / status / logs
# ---------------------------------------------------------------------------

cmd_start() {
  local build=0 tls=0 wait_timeout=300
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --build) build=1; shift ;;
      --tls) tls=1; shift ;;
      --wait-timeout) wait_timeout="$2"; shift 2 ;;
      *) log_err "Unknown option for start: $1"; exit 1 ;;
    esac
  done

  ensure_env_file
  [[ "$tls" -eq 1 ]] && require_certs
  compose_context "$tls"

  local up_args=(up -d --wait --wait-timeout "$wait_timeout")
  [[ "$build" -eq 1 ]] && up_args+=(--build)

  log_info "Starting stack (${COMPOSE_FILES[*]})..."
  compose "${up_args[@]}"

  log_ok "Stack is up."
  print_ready_banner "$tls"
}

print_ready_banner() {
  local tls="$1"
  compose_context "$tls"
  echo
  echo "  API           $BASE_URL"
  echo "  Health        $BASE_URL/actuator/health"
  echo "  Prometheus    http://localhost:9090"
  echo "  Grafana       http://localhost:3000  (admin/admin — dev-only default creds)"
  if [[ "$tls" -eq 1 ]]; then
    echo "  (TLS is self-signed — curl needs -k, browsers need a security bypass/CA import)"
  fi
  if [[ -f "$ENV_FILE" ]] && command -v node >/dev/null 2>&1; then
    load_env
    echo
    echo "  Demo JWT (CUSTOMER, $DEFAULT_CUSTOMER_ID):"
    echo "    $(mint_token CUSTOMER "$DEFAULT_CUSTOMER_ID" 2>/dev/null || echo '(mint failed — see ./dev.sh seed for diagnostics)')"
  fi
  echo
  echo "  Next: ./dev.sh seed     (wait for first ingestion cycle + example query)"
  echo "        ./dev.sh status   ./dev.sh logs -f"
  echo
}

cmd_stop() {
  local tls=0 volumes=0
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --tls) tls=1; shift ;;
      --volumes|-v) volumes=1; shift ;;
      *) log_err "Unknown option for stop: $1"; exit 1 ;;
    esac
  done
  compose_context "$tls"

  if [[ "$volumes" -eq 1 ]]; then
    log_warn "This deletes the Postgres data volume (all local demo data). Continue? [y/N]"
    read -r -p "> " confirm
    if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
      log_info "Aborted."
      return 0
    fi
    compose down -v --remove-orphans
    log_ok "Stack stopped, volumes removed."
  else
    compose down --remove-orphans
    log_ok "Stack stopped (data volume kept — use 'stop --volumes' to wipe it)."
  fi
}

cmd_restart() {
  # stop only understands --tls (not --build/--wait-timeout), so scan for it
  # rather than forwarding start's full flag set to stop verbatim.
  local tls=0
  for arg in "$@"; do
    [[ "$arg" == "--tls" ]] && tls=1
  done
  if [[ "$tls" -eq 1 ]]; then
    cmd_stop --tls
  else
    cmd_stop
  fi
  cmd_start "$@"
}

cmd_status() {
  local tls=0
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --tls) tls=1; shift ;;
      *) log_err "Unknown option for status: $1"; exit 1 ;;
    esac
  done
  compose_context "$tls"

  echo "Containers:"
  compose ps
  echo

  if curl_json "$BASE_URL/actuator/health" -o /tmp/dev-sh-health.json 2>/dev/null; then
    if command -v jq >/dev/null 2>&1; then
      log_ok "API health ($BASE_URL): $(jq -r '.status' /tmp/dev-sh-health.json)"
    else
      log_ok "API health ($BASE_URL): reachable (install jq for a parsed summary)"
    fi
  else
    log_warn "API not reachable at $BASE_URL. Is the stack started? ./dev.sh start"
    rm -f /tmp/dev-sh-health.json
    return 0
  fi
  rm -f /tmp/dev-sh-health.json

  # /actuator/health shows no per-source detail at the default show-details
  # setting (never, for anonymous callers) — /v1/admin/sources is the real
  # source of truth for ingestion status, so use that instead.
  if [[ -f "$ENV_FILE" ]] && command -v node >/dev/null 2>&1; then
    load_env
    local admin_token
    if admin_token="$(mint_token ADMIN "$DEFAULT_CUSTOMER_ID" 2>/dev/null)"; then
      echo "Source sync status:"
      if command -v jq >/dev/null 2>&1; then
        curl_json -H "Authorization: Bearer $admin_token" "$BASE_URL/v1/admin/sources" 2>/dev/null \
          | jq -r '.sources[]? | "  \(.id): \(.status)  (freshness: \(.freshnessStatus // "n/a"))"' \
          || log_warn "Could not reach /v1/admin/sources."
      else
        curl_json -H "Authorization: Bearer $admin_token" "$BASE_URL/v1/admin/sources" 2>/dev/null || true
        echo
      fi
    fi
  fi
}

cmd_logs() {
  local follow=0 tail=200 tls=0
  local services=()
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -f|--follow) follow=1; shift ;;
      --tail) tail="$2"; shift 2 ;;
      --tls) tls=1; shift ;;
      *) services+=("$1"); shift ;;
    esac
  done
  compose_context "$tls"
  local args=(logs --tail "$tail")
  [[ "$follow" -eq 1 ]] && args+=(-f)
  compose "${args[@]}" "${services[@]}"
}

# ---------------------------------------------------------------------------
# seed
# ---------------------------------------------------------------------------

cmd_seed() {
  local timeout=90 tls=0 customer_id="$DEFAULT_CUSTOMER_ID"
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --timeout) timeout="$2"; shift 2 ;;
      --tls) tls=1; shift ;;
      --customer-id) customer_id="$2"; shift 2 ;;
      *) log_err "Unknown option for seed: $1"; exit 1 ;;
    esac
  done
  require_cmd node
  require_cmd curl
  compose_context "$tls"
  load_env

  log_info "Waiting for $BASE_URL/actuator/health ..."
  local waited=0
  until curl -fsS $CURL_TLS_FLAG "$BASE_URL/actuator/health" >/dev/null 2>&1; do
    if [[ "$waited" -ge "$timeout" ]]; then
      log_err "API did not become healthy within ${timeout}s. Try: ./dev.sh logs transaction-api"
      exit 1
    fi
    sleep 3; waited=$((waited + 3))
  done
  log_ok "API is healthy."

  log_info "Minting an ADMIN token and waiting for every source to complete an ingestion cycle" \
           "(the scheduler runs every APP_INGESTION_INTERVAL_MS, 60s by default)..."
  local admin_token
  admin_token="$(mint_token ADMIN "$customer_id")"

  waited=0
  local all_success=0
  while [[ "$waited" -lt "$timeout" ]]; do
    local body
    body="$(curl -fsS $CURL_TLS_FLAG -H "Authorization: Bearer $admin_token" "$BASE_URL/v1/admin/sources" || echo '{}')"
    if command -v jq >/dev/null 2>&1; then
      if [[ "$(echo "$body" | jq -r '[.sources[]?.status] | all(. == "SUCCESS") and (length > 0)')" == "true" ]]; then
        all_success=1
        break
      fi
    else
      # Without jq, fall back to a crude but effective substring check.
      if echo "$body" | grep -q '"status":"SUCCESS"' && ! echo "$body" | grep -q '"status":"INITIAL"\|"status":"FAILED"'; then
        all_success=1
        break
      fi
    fi
    sleep 5; waited=$((waited + 5))
  done

  if [[ "$all_success" -eq 1 ]]; then
    log_ok "All configured sources report SUCCESS."
  else
    log_warn "Timed out after ${timeout}s waiting for all sources to succeed — showing current status anyway:"
  fi
  if command -v jq >/dev/null 2>&1; then
    curl -fsS $CURL_TLS_FLAG -H "Authorization: Bearer $admin_token" "$BASE_URL/v1/admin/sources" | jq .
  else
    curl -fsS $CURL_TLS_FLAG -H "Authorization: Bearer $admin_token" "$BASE_URL/v1/admin/sources"
    echo
  fi

  log_info "Querying the seeded demo customer ($customer_id) as a taste of the data:"
  local customer_token
  customer_token="$(mint_token CUSTOMER "$customer_id")"
  if command -v jq >/dev/null 2>&1; then
    curl -fsS $CURL_TLS_FLAG -H "Authorization: Bearer $customer_token" \
      "$BASE_URL/v1/customers/$customer_id/transactions?limit=5" | jq .
  else
    curl -fsS $CURL_TLS_FLAG -H "Authorization: Bearer $customer_token" \
      "$BASE_URL/v1/customers/$customer_id/transactions?limit=5"
    echo
  fi

  echo
  log_ok "Demo data is flowing. Reusable tokens:"
  echo "  CUSTOMER: $customer_token"
  echo "  ADMIN:    $admin_token"
  echo
  echo "  curl -H \"Authorization: Bearer \$TOKEN\" \"$BASE_URL/v1/customers/$customer_id/summary\""
}

# ---------------------------------------------------------------------------
# test
# ---------------------------------------------------------------------------

# The subset of the suite that needs no Testcontainers/Docker — verified by
# running it in this environment (no Docker daemon available here) on
# 2026-09-25. IngestionServiceTest and IdempotencyTest are deliberately
# excluded: both need a real Spring context backed by Testcontainers
# (IdempotencyTest extends AbstractIntegrationTest; IngestionServiceTest is
# @SpringBootTest) — see docs/principal_engineer_review_report.md §10.5,
# which mistakenly included IdempotencyTest in this list; corrected here.
# TransactionRepositoryTest, KafkaTransactionSourceTest, S3TransactionSourceTest,
# AdminSourcesEndpointTest, ApiIsolationTest, ApiPaginationAndFilterTest,
# ApiSummaryCurrencyTest, and ApiValidationTest are also excluded for the same
# reason (@SpringBootTest / Testcontainers KafkaContainer / GenericContainer).
# SourceAdapterNormalizationTest no longer exists post-ADR-011 (config-driven
# source registry, landed on main 2026-09-25) — replaced by SourceNormalizerTest
# plus the per-transport tests below.
UNIT_ONLY_TESTS="KeysetCursorTest,ResilienceTest,QuarantineTest,SyncFailureTest,RuleBasedCategorizerTest,CustomerAccessValidatorTest,SourceNormalizerTest,HttpTransactionSourceTest,MockTransactionSourceTest,SyncHealthIndicatorTest"

cmd_test() {
  local mode="full"
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --unit) mode="unit"; shift ;;
      --e2e) mode="e2e"; shift ;;
      *) log_err "Unknown option for test: $1"; exit 1 ;;
    esac
  done

  case "$mode" in
    unit)
      require_cmd mvn
      log_info "Running the Testcontainers-free subset (no Docker required)..."
      exec "$ROOT/scripts/test.sh" -q test -Dtest="$UNIT_ONLY_TESTS" -DfailIfNoTests=false
      ;;
    full)
      log_info "Running the full suite (unit + Testcontainers integration; needs Docker)..."
      exec "$ROOT/scripts/test.sh" test
      ;;
    e2e)
      require_cmd node
      require_cmd npm
      log_info "Running Playwright E2E against a running stack at \$E2E_BASE_URL (default http://localhost:8080)."
      log_info "Make sure the stack is started first: ./dev.sh start && ./dev.sh seed"
      npm ci
      npx playwright install --with-deps chromium
      set +e
      npx playwright test --reporter=json > "$ROOT/playwright-results.json"
      set -e
      # Pass/fail is decided by e2e-assert.mjs (checks real failures AND
      # skips), not Playwright's own exit code — see its header comment and
      # docs/principal_engineer_review_report.md C-01.
      node "$ROOT/scripts/e2e-assert.mjs" "$ROOT/playwright-results.json"
      ;;
  esac
}

# ---------------------------------------------------------------------------
# perf
# ---------------------------------------------------------------------------

cmd_perf() {
  # Defaults match scripts/load-test.js's own env-var contract (LOAD_TEST_*),
  # not a wrapper-invented one - see that script's header comment for the
  # full set (LOAD_TEST_RAMP/HOLD, SOAK_VUS/DURATION) if you need finer
  # control than these flags expose; just export them before calling perf.
  local scenario=smoke vus=20 hold=2m customer_id="$DEFAULT_CUSTOMER_ID" tls=0
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --scenario) scenario="$2"; shift 2 ;;
      --vus) vus="$2"; shift 2 ;;
      --hold) hold="$2"; shift 2 ;;
      --customer-id) customer_id="$2"; shift 2 ;;
      --tls) tls=1; shift ;;
      *) log_err "Unknown option for perf: $1"; exit 1 ;;
    esac
  done

  compose_context "$tls"
  load_env

  if ! curl -fsS $CURL_TLS_FLAG "$BASE_URL/actuator/health" >/dev/null 2>&1; then
    log_err "API not reachable at $BASE_URL. Start it first: ./dev.sh start"
    exit 1
  fi

  log_info "Running scripts/load-test.js: SCENARIO=$scenario LOAD_TEST_VUS=$vus LOAD_TEST_HOLD=$hold BASE_URL=$BASE_URL"
  log_info "Default scenario is 'smoke' (fast pipeline sanity, ~10s) - pass --scenario load|soak|all" \
           "for a real capacity run. Deliberately not wired into CI (shared-runner timings are noise" \
           "for a p99 SLO); see IMPLEMENTATION_PLAN.md Phase 7 for the last verified numbers."

  # The script mints its own token in setup() if LOAD_TEST_TOKEN is absent,
  # using LOAD_TEST_JWT_SECRET (or a test-only default that won't match a
  # real running server). Pass the real secret explicitly so it mints
  # against whatever this stack is actually using - same reasoning as the
  # mint-jwt.mjs fallback warning (L-03).
  if command -v k6 >/dev/null 2>&1; then
    LOAD_TEST_BASE_URL="$BASE_URL" LOAD_TEST_CUSTOMER_ID="$customer_id" \
      LOAD_TEST_JWT_SECRET="$APP_SECURITY_JWT_SECRET" \
      SCENARIO="$scenario" LOAD_TEST_VUS="$vus" LOAD_TEST_HOLD="$hold" \
      k6 run "$ROOT/scripts/load-test.js"
  else
    log_info "Local k6 binary not found — running via the official grafana/k6 Docker image."
    local docker_base_url="$BASE_URL"
    if [[ "$BASE_URL" == *localhost* ]]; then
      docker_base_url="${BASE_URL/localhost/host.docker.internal}"
    fi
    docker run --rm -i \
      --add-host=host.docker.internal:host-gateway \
      -e LOAD_TEST_BASE_URL="$docker_base_url" -e LOAD_TEST_CUSTOMER_ID="$customer_id" \
      -e LOAD_TEST_JWT_SECRET="$APP_SECURITY_JWT_SECRET" \
      -e SCENARIO="$scenario" -e LOAD_TEST_VUS="$vus" -e LOAD_TEST_HOLD="$hold" \
      -v "$ROOT/scripts:/scripts:ro" \
      grafana/k6 run /scripts/load-test.js
  fi
}

# ---------------------------------------------------------------------------
# dispatch
# ---------------------------------------------------------------------------

main() {
  local cmd="${1:-help}"
  [[ $# -gt 0 ]] && shift

  case "$cmd" in
    setup) cmd_setup "$@" ;;
    certs) cmd_certs "$@" ;;
    start) cmd_start "$@" ;;
    stop) cmd_stop "$@" ;;
    restart) cmd_restart "$@" ;;
    status) cmd_status "$@" ;;
    logs) cmd_logs "$@" ;;
    seed|setup-data) cmd_seed "$@" ;;
    test) cmd_test "$@" ;;
    perf|load-test) cmd_perf "$@" ;;
    clean) cmd_stop --volumes "$@" ;;
    help|-h|--help) cmd_help ;;
    *)
      log_err "Unknown command: $cmd"
      cmd_help
      exit 1
      ;;
  esac
}

main "$@"
