apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transact.fullname" . }}-secret
  labels:
    app: transact
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secret.springDatasourcePassword | quote }}
  APP_SECURITY_JWT_SECRET: {{ .Values.secret.appSecurityJwtSecret | quote }}
